# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Interfaz Drone2iBtvzB.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import dpad_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1145, 864)
        MainWindow.setMaximumSize(QSize(1920, 1080))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(Qt.NoContextMenu)
        MainWindow.setWindowTitle(u"SmartDrone")
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        MainWindow.setStyleSheet(u"background-color: rgb(36, 161, 233);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(1920, 1080))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 50, 1141, 811))
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.grupo_control_remoto_drone = QGroupBox(self.frame_3)
        self.grupo_control_remoto_drone.setObjectName(u"grupo_control_remoto_drone")
        self.grupo_control_remoto_drone.setGeometry(QRect(620, 490, 511, 311))
        self.grupo_control_remoto_drone.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_7 = QLabel(self.grupo_control_remoto_drone)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 210, 61, 31))
        self.label_5 = QLabel(self.grupo_control_remoto_drone)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 60, 71, 31))
        self.ingres_angulo = QLineEdit(self.grupo_control_remoto_drone)
        self.ingres_angulo.setObjectName(u"ingres_angulo")
        self.ingres_angulo.setGeometry(QRect(20, 210, 91, 31))
        self.ingres_angulo.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.ingreso_altura = QLineEdit(self.grupo_control_remoto_drone)
        self.ingreso_altura.setObjectName(u"ingreso_altura")
        self.ingreso_altura.setGeometry(QRect(20, 160, 91, 31))
        self.ingreso_altura.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.ingreso_latitud = QLineEdit(self.grupo_control_remoto_drone)
        self.ingreso_latitud.setObjectName(u"ingreso_latitud")
        self.ingreso_latitud.setGeometry(QRect(20, 110, 91, 31))
        self.ingreso_latitud.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_9 = QLabel(self.grupo_control_remoto_drone)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 160, 51, 31))
        self.botton_control_drone = QPushButton(self.grupo_control_remoto_drone)
        self.botton_control_drone.setObjectName(u"botton_control_drone")
        self.botton_control_drone.setGeometry(QRect(70, 260, 89, 31))
        self.label_6 = QLabel(self.grupo_control_remoto_drone)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 110, 61, 31))
        self.Ingreso_longitud = QLineEdit(self.grupo_control_remoto_drone)
        self.Ingreso_longitud.setObjectName(u"Ingreso_longitud")
        self.Ingreso_longitud.setGeometry(QRect(20, 60, 91, 31))
        self.Ingreso_longitud.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_24 = QLabel(self.grupo_control_remoto_drone)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(200, 60, 21, 31))
        self.label_25 = QLabel(self.grupo_control_remoto_drone)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(200, 110, 21, 31))
        self.label_26 = QLabel(self.grupo_control_remoto_drone)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(200, 160, 21, 31))
        self.label_27 = QLabel(self.grupo_control_remoto_drone)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(200, 210, 21, 31))
        self.line = QFrame(self.grupo_control_remoto_drone)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(233, 30, 20, 271))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_31 = QLabel(self.grupo_control_remoto_drone)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(270, 30, 211, 211))
        self.label_31.setStyleSheet(u"image: url(:/Dpad/Dpad.jpeg);")
        self.arriba = QPushButton(self.grupo_control_remoto_drone)
        self.arriba.setObjectName(u"arriba")
        self.arriba.setGeometry(QRect(350, 30, 51, 71))
        self.arriba.setStyleSheet(u"border-image: url(:/up/Up.jpeg);\n"
"background-color: rgb(24, 21, 22);")
        self.izquierda = QPushButton(self.grupo_control_remoto_drone)
        self.izquierda.setObjectName(u"izquierda")
        self.izquierda.setGeometry(QRect(270, 110, 71, 51))
        self.izquierda.setStyleSheet(u"border-image: url(:/left/Left.jpeg);")
        self.derecha = QPushButton(self.grupo_control_remoto_drone)
        self.derecha.setObjectName(u"derecha")
        self.derecha.setGeometry(QRect(410, 110, 71, 51))
        self.derecha.setStyleSheet(u"border-image: url(:/right/right.jpeg);")
        self.abajo = QPushButton(self.grupo_control_remoto_drone)
        self.abajo.setObjectName(u"abajo")
        self.abajo.setGeometry(QRect(350, 170, 51, 71))
        self.abajo.setStyleSheet(u"border-image: url(:/down/Down.jpeg);")
        self.diag_upleft = QPushButton(self.grupo_control_remoto_drone)
        self.diag_upleft.setObjectName(u"diag_upleft")
        self.diag_upleft.setGeometry(QRect(270, 30, 71, 71))
        self.diag_downleft = QPushButton(self.grupo_control_remoto_drone)
        self.diag_downleft.setObjectName(u"diag_downleft")
        self.diag_downleft.setGeometry(QRect(270, 170, 71, 71))
        self.diag_downright = QPushButton(self.grupo_control_remoto_drone)
        self.diag_downright.setObjectName(u"diag_downright")
        self.diag_downright.setGeometry(QRect(410, 170, 71, 71))
        self.diag_upright = QPushButton(self.grupo_control_remoto_drone)
        self.diag_upright.setObjectName(u"diag_upright")
        self.diag_upright.setGeometry(QRect(410, 30, 71, 71))
        self.stop = QPushButton(self.grupo_control_remoto_drone)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(340, 100, 71, 71))
        self.up = QPushButton(self.grupo_control_remoto_drone)
        self.up.setObjectName(u"up")
        self.up.setGeometry(QRect(280, 250, 89, 41))
        self.down = QPushButton(self.grupo_control_remoto_drone)
        self.down.setObjectName(u"down")
        self.down.setGeometry(QRect(390, 250, 89, 41))
        self.groupBox_2 = QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 751, 471))
        self.groupBox_2.setStyleSheet(u"background-color: rgba(210, 216, 230, 148);")
        self.frame = QFrame(self.groupBox_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 30, 731, 431))
        self.frame.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.groupBox_6 = QGroupBox(self.frame_3)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(770, 10, 361, 471))
        self.groupBox_6.setStyleSheet(u"background-color: rgba(210, 216, 230, 148);\n"
"")
        self.widget_2 = QWidget(self.groupBox_6)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(0, 30, 341, 431))
        self.widget_2.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.grupo_Control_Monitoreo = QGroupBox(self.frame_3)
        self.grupo_Control_Monitoreo.setObjectName(u"grupo_Control_Monitoreo")
        self.grupo_Control_Monitoreo.setGeometry(QRect(10, 490, 321, 111))
        self.grupo_Control_Monitoreo.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_17 = QLabel(self.grupo_Control_Monitoreo)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(130, 30, 191, 31))
        self.botton_alarma_nvr = QPushButton(self.grupo_Control_Monitoreo)
        self.botton_alarma_nvr.setObjectName(u"botton_alarma_nvr")
        self.botton_alarma_nvr.setGeometry(QRect(20, 70, 89, 31))
        self.botton_videos_nvr = QPushButton(self.grupo_Control_Monitoreo)
        self.botton_videos_nvr.setObjectName(u"botton_videos_nvr")
        self.botton_videos_nvr.setGeometry(QRect(20, 30, 89, 31))
        self.label_18 = QLabel(self.grupo_Control_Monitoreo)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 70, 161, 31))
        self.grupo_Control_Operacion_Drone = QGroupBox(self.frame_3)
        self.grupo_Control_Operacion_Drone.setObjectName(u"grupo_Control_Operacion_Drone")
        self.grupo_Control_Operacion_Drone.setGeometry(QRect(10, 610, 321, 191))
        self.grupo_Control_Operacion_Drone.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.botton_stop_drone = QPushButton(self.grupo_Control_Operacion_Drone)
        self.botton_stop_drone.setObjectName(u"botton_stop_drone")
        self.botton_stop_drone.setGeometry(QRect(170, 60, 141, 61))
        self.botton_start_drone = QPushButton(self.grupo_Control_Operacion_Drone)
        self.botton_start_drone.setObjectName(u"botton_start_drone")
        self.botton_start_drone.setGeometry(QRect(10, 60, 141, 61))
        self.label_29 = QLabel(self.grupo_Control_Operacion_Drone)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 130, 141, 21))
        self.label_30 = QLabel(self.grupo_Control_Operacion_Drone)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(170, 130, 141, 21))
        self.grupo_telemetria_drone = QGroupBox(self.frame_3)
        self.grupo_telemetria_drone.setObjectName(u"grupo_telemetria_drone")
        self.grupo_telemetria_drone.setGeometry(QRect(340, 490, 271, 311))
        self.grupo_telemetria_drone.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_14 = QLabel(self.grupo_telemetria_drone)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(130, 90, 61, 21))
        self.lcd_longitud_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_longitud_drone.setObjectName(u"lcd_longitud_drone")
        self.lcd_longitud_drone.setGeometry(QRect(10, 30, 111, 41))
        self.lcd_longitud_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_8 = QLabel(self.grupo_telemetria_drone)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(130, 190, 51, 21))
        self.label_10 = QLabel(self.grupo_telemetria_drone)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 140, 51, 20))
        self.lcd_latitud_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_latitud_drone.setObjectName(u"lcd_latitud_drone")
        self.lcd_latitud_drone.setGeometry(QRect(10, 80, 111, 41))
        self.lcd_latitud_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_13 = QLabel(self.grupo_telemetria_drone)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 40, 71, 20))
        self.lcd_rotacion_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_rotacion_drone.setObjectName(u"lcd_rotacion_drone")
        self.lcd_rotacion_drone.setGeometry(QRect(10, 180, 111, 41))
        self.lcd_rotacion_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.lcd_altura_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_altura_drone.setObjectName(u"lcd_altura_drone")
        self.lcd_altura_drone.setGeometry(QRect(10, 130, 111, 41))
        self.lcd_altura_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label = QLabel(self.grupo_telemetria_drone)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(200, 30, 21, 41))
        self.label_2 = QLabel(self.grupo_telemetria_drone)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 80, 21, 41))
        self.label_3 = QLabel(self.grupo_telemetria_drone)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(190, 130, 21, 41))
        self.label_23 = QLabel(self.grupo_telemetria_drone)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(190, 180, 31, 41))
        self.label_16 = QLabel(self.grupo_telemetria_drone)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(130, 240, 141, 20))
        self.lcd_tiempo_vuelo = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_tiempo_vuelo.setObjectName(u"lcd_tiempo_vuelo")
        self.lcd_tiempo_vuelo.setGeometry(QRect(10, 230, 111, 41))
        self.lcd_tiempo_vuelo.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.grupo_control_remoto_drone.setTitle(QCoreApplication.translate("MainWindow", u"Control Remoto Drone", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Angulo", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Longitud", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Altura", None))
        self.botton_control_drone.setText(QCoreApplication.translate("MainWindow", u"Mover", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Latitud", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"(\u00b0)", None))
        self.label_31.setText("")
        self.arriba.setText("")
        self.izquierda.setText("")
        self.derecha.setText("")
        self.abajo.setText("")
        self.diag_upleft.setText("")
        self.diag_downleft.setText("")
        self.diag_downright.setText("")
        self.diag_upright.setText("")
        self.stop.setText("")
        self.up.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.down.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Camara Drone", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Mapa Drone", None))
        self.grupo_Control_Monitoreo.setTitle(QCoreApplication.translate("MainWindow", u"Control Monitoreo", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Registros grabaciones NVR", None))
        self.botton_alarma_nvr.setText(QCoreApplication.translate("MainWindow", u"Alarmas", None))
        self.botton_videos_nvr.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Registros Alarmas NVR", None))
        self.grupo_Control_Operacion_Drone.setTitle(QCoreApplication.translate("MainWindow", u"Control Operacion Drone ", None))
        self.botton_stop_drone.setText(QCoreApplication.translate("MainWindow", u"Retornar", None))
        self.botton_start_drone.setText(QCoreApplication.translate("MainWindow", u"Inicio", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"    Despegar Drone", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"    Aterrizar en base", None))
        self.grupo_telemetria_drone.setTitle(QCoreApplication.translate("MainWindow", u"Telemetria Drone", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Latitud", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Angulo", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Altura", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Longitud", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"(\u00b0)", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Tiempo de vuelo (s)", None))
        pass
    # retranslateUi

