# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Interfaz Drone2csfFhS.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from qwt_dial import QwtDial
from qwt_thermo import QwtThermo
from qwt_text_label import QwtTextLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1149, 874)
        MainWindow.setMaximumSize(QSize(1149, 874))
        MainWindow.setStyleSheet(u"background-color: rgb(36, 161, 233);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 660, 381, 191))
        self.groupBox.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.TextLabel_2 = QwtTextLabel(self.groupBox)
        self.TextLabel_2.setObjectName(u"TextLabel_2")
        self.TextLabel_2.setGeometry(QRect(40, 120, 100, 20))
        self.TextLabel = QwtTextLabel(self.groupBox)
        self.TextLabel.setObjectName(u"TextLabel")
        self.TextLabel.setGeometry(QRect(200, 120, 161, 21))
        self.pushButton_5 = QPushButton(self.groupBox)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(200, 40, 161, 61))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(220, 150, 121, 31))
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 150, 91, 31))
        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 40, 161, 61))
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(400, 540, 471, 311))
        self.groupBox_4.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(360, 220, 61, 31))
        self.lcd_long = QLCDNumber(self.groupBox_4)
        self.lcd_long.setObjectName(u"lcd_long")
        self.lcd_long.setGeometry(QRect(320, 70, 111, 41))
        self.lcd_long.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.Rotation_Dial = QwtDial(self.groupBox_4)
        self.Rotation_Dial.setObjectName(u"Rotation_Dial")
        self.Rotation_Dial.setGeometry(QRect(10, 30, 211, 191))
        self.Rotation_Dial.setProperty("upperBound", 360.000000000000000)
        self.Rotation_Dial.setProperty("scaleMaxMajor", 34)
        self.Rotation_Dial.setProperty("scaleMaxMinor", 2)
        self.Rotation_Dial.setProperty("totalSteps", 1u)
        self.Rotation_Dial.setProperty("pageSteps", 1u)
        self.Rotation_Dial.setProperty("readOnly", True)
        self.Rotation_Dial.setProperty("lineWidth", 4)
        self.Rotation_Dial.setProperty("origin", 270.000000000000000)
        self.Rotation_Dial.setProperty("minScaleArc", 0.000000000000000)
        self.Rotation_Dial.setProperty("maxScaleArc", 360.000000000000000)
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(70, 280, 51, 21))
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(240, 280, 51, 20))
        self.lcd_lat = QLCDNumber(self.groupBox_4)
        self.lcd_lat.setObjectName(u"lcd_lat")
        self.lcd_lat.setGeometry(QRect(320, 170, 111, 41))
        self.lcd_lat.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(360, 120, 71, 31))
        self.lcd_rotation = QLCDNumber(self.groupBox_4)
        self.lcd_rotation.setObjectName(u"lcd_rotation")
        self.lcd_rotation.setGeometry(QRect(30, 230, 101, 41))
        self.lcd_rotation.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.lcd_alt = QLCDNumber(self.groupBox_4)
        self.lcd_alt.setObjectName(u"lcd_alt")
        self.lcd_alt.setGeometry(QRect(190, 230, 101, 41))
        self.lcd_alt.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label = QLabel(self.groupBox_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(440, 70, 21, 41))
        self.label_2 = QLabel(self.groupBox_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(440, 170, 21, 41))
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(300, 230, 21, 41))
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(140, 230, 21, 41))
        self.altura = QwtThermo(self.groupBox_4)
        self.altura.setObjectName(u"altura")
        self.altura.setGeometry(QRect(220, 30, 71, 201))
        self.altura.setProperty("upperBound", 10.000000000000000)
        self.altura.setProperty("scaleMaxMajor", 5)
        self.altura.setProperty("scaleMaxMinor", 4)
        self.altura.setProperty("scaleStepSize", 1.000000000000000)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(880, 540, 251, 311))
        self.groupBox_5.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_7 = QLabel(self.groupBox_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(150, 200, 61, 31))
        self.label_5 = QLabel(self.groupBox_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(150, 50, 71, 31))
        self.textBrowser_3 = QTextBrowser(self.groupBox_5)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(40, 200, 91, 31))
        self.textBrowser_3.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.textBrowser_4 = QTextBrowser(self.groupBox_5)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(40, 150, 91, 31))
        self.textBrowser_4.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.textBrowser_2 = QTextBrowser(self.groupBox_5)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(40, 100, 91, 31))
        self.textBrowser_2.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_9 = QLabel(self.groupBox_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(150, 150, 51, 31))
        self.pushButton = QPushButton(self.groupBox_5)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(80, 260, 89, 25))
        self.label_6 = QLabel(self.groupBox_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 100, 61, 31))
        self.textBrowser = QTextBrowser(self.groupBox_5)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(40, 50, 91, 31))
        self.textBrowser.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_24 = QLabel(self.groupBox_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(220, 50, 21, 31))
        self.label_25 = QLabel(self.groupBox_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(220, 100, 21, 31))
        self.label_26 = QLabel(self.groupBox_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(220, 150, 21, 31))
        self.label_27 = QLabel(self.groupBox_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(220, 200, 21, 31))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 540, 381, 111))
        self.groupBox_3.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_17 = QLabel(self.groupBox_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(130, 30, 191, 31))
        self.pushButton_6 = QPushButton(self.groupBox_3)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(20, 70, 89, 31))
        self.pushButton_7 = QPushButton(self.groupBox_3)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(20, 30, 89, 31))
        self.label_18 = QLabel(self.groupBox_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 70, 161, 31))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 60, 751, 471))
        self.groupBox_2.setStyleSheet(u"background-color: rgba(210, 216, 230, 148);")
        self.frame = QFrame(self.groupBox_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 30, 731, 431))
        self.frame.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(770, 60, 361, 471))
        self.groupBox_6.setStyleSheet(u"background-color: rgba(210, 216, 230, 148);\n"
"")
        self.widget_2 = QWidget(self.groupBox_6)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(10, 30, 341, 431))
        self.widget_2.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Control Operacion Drone ", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Retornar", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Tiempo de vuelo", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Temperatura", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Inicio", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Telemetria Drone", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Latitud", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Angulo", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Altura", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Longitud", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"(\u00b0)", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Control Remoto Drone", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Angulo", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Longitud", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Altura", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Mover", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Latitud", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"(\u00b0)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Control Monitoreo", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Registros grabaciones NVR", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Alarmas", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Registros Alarmas NVR", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Camara Drone", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Mapa Drone", None))
    # retranslateUi

