# -- coding: utf-8 --

################################################################################
## Form generated from reading UI file 'Interfaz Drone2ikfAVP.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1145, 864)
        MainWindow.setMaximumSize(QSize(1920, 1080))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(Qt.NoContextMenu)
        MainWindow.setWindowTitle(u"SmartDrone")
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        MainWindow.setStyleSheet(u"background-color: rgb(36, 161, 233);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMaximumSize(QSize(1920, 1080))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 50, 1141, 811))
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Plain)
        self.grupo_control_remoto_drone = QGroupBox(self.frame_3)
        self.grupo_control_remoto_drone.setObjectName(u"grupo_control_remoto_drone")
        self.grupo_control_remoto_drone.setGeometry(QRect(880, 490, 251, 311))
        self.grupo_control_remoto_drone.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_7 = QLabel(self.grupo_control_remoto_drone)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(150, 200, 61, 31))
        self.label_5 = QLabel(self.grupo_control_remoto_drone)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(150, 50, 71, 31))
        self.ingres_angulo = QTextBrowser(self.grupo_control_remoto_drone)
        self.ingres_angulo.setObjectName(u"ingres_angulo")
        self.ingres_angulo.setGeometry(QRect(40, 200, 91, 31))
        self.ingres_angulo.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.ingreso_altura = QTextBrowser(self.grupo_control_remoto_drone)
        self.ingreso_altura.setObjectName(u"ingreso_altura")
        self.ingreso_altura.setGeometry(QRect(40, 150, 91, 31))
        self.ingreso_altura.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.ingreso_latitud = QTextBrowser(self.grupo_control_remoto_drone)
        self.ingreso_latitud.setObjectName(u"ingreso_latitud")
        self.ingreso_latitud.setGeometry(QRect(40, 100, 91, 31))
        self.ingreso_latitud.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_9 = QLabel(self.grupo_control_remoto_drone)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(150, 150, 51, 31))
        self.botton_control_drone = QPushButton(self.grupo_control_remoto_drone)
        self.botton_control_drone.setObjectName(u"botton_control_drone")
        self.botton_control_drone.setGeometry(QRect(80, 260, 89, 25))
        self.label_6 = QLabel(self.grupo_control_remoto_drone)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(150, 100, 61, 31))
        self.Ingreso_longitud = QTextBrowser(self.grupo_control_remoto_drone)
        self.Ingreso_longitud.setObjectName(u"Ingreso_longitud")
        self.Ingreso_longitud.setGeometry(QRect(40, 50, 91, 31))
        self.Ingreso_longitud.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_24 = QLabel(self.grupo_control_remoto_drone)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(220, 50, 21, 31))
        self.label_25 = QLabel(self.grupo_control_remoto_drone)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(220, 100, 21, 31))
        self.label_26 = QLabel(self.grupo_control_remoto_drone)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(220, 150, 21, 31))
        self.label_27 = QLabel(self.grupo_control_remoto_drone)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(220, 200, 21, 31))
        self.groupBox_2 = QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 751, 471))
        self.groupBox_2.setStyleSheet(u"background-color: rgba(210, 216, 230, 148);")
        self.frame = QFrame(self.groupBox_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 30, 731, 431))
        self.frame.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.groupBox_6 = QGroupBox(self.frame_3)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(770, 10, 361, 471))
        self.groupBox_6.setStyleSheet(u"background-color: rgba(210, 216, 230, 148);\n"
"")
        self.widget_2 = QWidget(self.groupBox_6)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(10, 30, 341, 431))
        self.widget_2.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.grupo_Control_Monitoreo = QGroupBox(self.frame_3)
        self.grupo_Control_Monitoreo.setObjectName(u"grupo_Control_Monitoreo")
        self.grupo_Control_Monitoreo.setGeometry(QRect(10, 490, 381, 111))
        self.grupo_Control_Monitoreo.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_17 = QLabel(self.grupo_Control_Monitoreo)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(130, 30, 191, 31))
        self.botton_alarma_nvr = QPushButton(self.grupo_Control_Monitoreo)
        self.botton_alarma_nvr.setObjectName(u"botton_alarma_nvr")
        self.botton_alarma_nvr.setGeometry(QRect(20, 70, 89, 31))
        self.botton_videos_nvr = QPushButton(self.grupo_Control_Monitoreo)
        self.botton_videos_nvr.setObjectName(u"botton_videos_nvr")
        self.botton_videos_nvr.setGeometry(QRect(20, 30, 89, 31))
        self.label_18 = QLabel(self.grupo_Control_Monitoreo)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 70, 161, 31))
        self.grupo_Control_Operacion_Drone = QGroupBox(self.frame_3)
        self.grupo_Control_Operacion_Drone.setObjectName(u"grupo_Control_Operacion_Drone")
        self.grupo_Control_Operacion_Drone.setGeometry(QRect(10, 610, 381, 191))
        self.grupo_Control_Operacion_Drone.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.botton_stop_drone = QPushButton(self.grupo_Control_Operacion_Drone)
        self.botton_stop_drone.setObjectName(u"botton_stop_drone")
        self.botton_stop_drone.setGeometry(QRect(200, 40, 161, 61))
        self.label_16 = QLabel(self.grupo_Control_Operacion_Drone)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(220, 150, 121, 31))
        self.label_15 = QLabel(self.grupo_Control_Operacion_Drone)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 150, 91, 31))
        self.botton_start_drone = QPushButton(self.grupo_Control_Operacion_Drone)
        self.botton_start_drone.setObjectName(u"botton_start_drone")
        self.botton_start_drone.setGeometry(QRect(10, 40, 161, 61))
        self.grupo_telemetria_drone = QGroupBox(self.frame_3)
        self.grupo_telemetria_drone.setObjectName(u"grupo_telemetria_drone")
        self.grupo_telemetria_drone.setGeometry(QRect(400, 490, 471, 311))
        self.grupo_telemetria_drone.setStyleSheet(u"background-color: rgb(210, 216, 230);")
        self.label_14 = QLabel(self.grupo_telemetria_drone)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(360, 220, 61, 31))
        self.lcd_longitud_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_longitud_drone.setObjectName(u"lcd_longitud_drone")
        self.lcd_longitud_drone.setGeometry(QRect(320, 70, 111, 41))
        self.lcd_longitud_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_8 = QLabel(self.grupo_telemetria_drone)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(70, 280, 51, 21))
        self.label_10 = QLabel(self.grupo_telemetria_drone)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(240, 280, 51, 20))
        self.lcd_latitud_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_latitud_drone.setObjectName(u"lcd_latitud_drone")
        self.lcd_latitud_drone.setGeometry(QRect(320, 170, 111, 41))
        self.lcd_latitud_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label_13 = QLabel(self.grupo_telemetria_drone)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(360, 120, 71, 31))
        self.lcd_rotacion_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_rotacion_drone.setObjectName(u"lcd_rotacion_drone")
        self.lcd_rotacion_drone.setGeometry(QRect(30, 230, 101, 41))
        self.lcd_rotacion_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.lcd_altura_drone = QLCDNumber(self.grupo_telemetria_drone)
        self.lcd_altura_drone.setObjectName(u"lcd_altura_drone")
        self.lcd_altura_drone.setGeometry(QRect(190, 230, 101, 41))
        self.lcd_altura_drone.setStyleSheet(u"background-color: rgb(238, 238, 236);")
        self.label = QLabel(self.grupo_telemetria_drone)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(440, 70, 21, 41))
        self.label_2 = QLabel(self.grupo_telemetria_drone)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(440, 170, 21, 41))
        self.label_3 = QLabel(self.grupo_telemetria_drone)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(300, 230, 21, 41))
        self.label_23 = QLabel(self.grupo_telemetria_drone)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(140, 230, 21, 41))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.grupo_control_remoto_drone.setTitle(QCoreApplication.translate("MainWindow", u"Control Remoto Drone", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Angulo", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Longitud", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Altura", None))
        self.botton_control_drone.setText(QCoreApplication.translate("MainWindow", u"Mover", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Latitud", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"(\u00b0)", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Camara Drone", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Mapa Drone", None))
        self.grupo_Control_Monitoreo.setTitle(QCoreApplication.translate("MainWindow", u"Control Monitoreo", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Registros grabaciones NVR", None))
        self.botton_alarma_nvr.setText(QCoreApplication.translate("MainWindow", u"Alarmas", None))
        self.botton_videos_nvr.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Registros Alarmas NVR", None))
        self.grupo_Control_Operacion_Drone.setTitle(QCoreApplication.translate("MainWindow", u"Control Operacion Drone ", None))
        self.botton_stop_drone.setText(QCoreApplication.translate("MainWindow", u"Retornar", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Tiempo de vuelo", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Temperatura", None))
        self.botton_start_drone.setText(QCoreApplication.translate("MainWindow", u"Inicio", None))
        self.grupo_telemetria_drone.setTitle(QCoreApplication.translate("MainWindow", u"Telemetria Drone", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Latitud", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Angulo", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Altura", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Longitud", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"(m)", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"(\u00b0)", None))
        pass